# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Sathvik Rajasekaran
title: 
email: 2sathvik@gmail.com
website: sathvik4142.github.io

# Social links
# twitter_username: facespics
github_username:  sathvik4142
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: sathvik-rajasekaran-40a21516a
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sathvik and I'm a senior at Lynbrook High School.

  I am most skilled in: <mark>AWS</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in mathematics and computer science, some of my other interests and hobbies are:
   - Reading
   - Gaming
   - Chesss

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
